# Generated by Django 3.1.6 on 2021-02-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BS_APP', '0002_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
